name: Push to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                         # Set your preferred AWS region
  ECR_REPOSITORY: my_ecr_repository             # Set your Amazon ECR repository name

permissions:
  contents: read

jobs:
  push-to-ecr:
    name: Build and Push Docker Image to Amazon ECR
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Build and push Docker image to Amazon ECR
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfile
          push: true
          tags: 396608798478.dkr.ecr.us-east-1.amazonaws.com/my_ecr_repository/my_ecr_repository:latest
          

   
