name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                         # Set this to your preferred AWS region
  ECR_REPOSITORY: my_ecr_repository             # Set this to your Amazon ECR repository name
