name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository (optional)
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: SSH into EC2 instance and deploy Docker container
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Docker is running
            sudo systemctl start docker || true

            # Pull the Docker image
            docker pull ${{ secrets.DOCKER_IMAGE }}

            # Stop and remove the existing container (if running)
            docker stop my_app || true
            docker rm my_app || true

            # Run the Docker container
            docker run -d --name my_app -p 80:3000 ${{ secrets.DOCKER_IMAGE }}
